### ISSUE TITLE
pod lacks a SEE ALSO section

### ISSUE THREAD

**Issue by tobyink** [xsawyerx/acme-rafl-everywhere#5]
I'd suggest including at least this link.

http://piuparts.debian.org/squeeze/maintainer/r/rafl@debian.org.html

**Comment by xsawyerx** [comment]
Actually, it _would_ make sense to add links to rafl-related stuff. We could include his MetaCPAN author page as well.

**Comment by xsawyerx** [comment]
Added. Thank you!

If you think of anything else (including more links), please let me know! :)
