### ISSUE TITLE
Feature Request: this module should include a selection of @rafl images...

### ISSUE THREAD

**Issue by genehack** [xsawyerx/acme-rafl-everywhere#7]
...suitable for use in talks (i.e., YAPCs, workshops, user group meetings, etc.)

**Comment by Getty** [comment]
Upvote!

**Comment by ubu** [comment]
+1

**Comment by xsawyerx** [comment]
Can someone help consolidate this? We can keep the images in the repo.
We could also install it in a shared directory (File::ShareDir) and have a method that returns that directory so you could link to it from slides or copy from it. What say you wise men? @genehack @Getty @ubu

**Comment by Getty** [comment]
The wise men agree..... 

The wise man @Getty can do it.....

The wise man requests pictures send to getty@cpan.org

**Comment by xsawyerx** [comment]
Thanks @Getty!

I'll add a section in the documentation requesting images be sent there as well!
