### ISSUE TITLE
rafl is so everywhere...

### ISSUE THREAD

**Issue by tobyink** [xsawyerx/acme-rafl-everywhere#9]
... the next version of Debian is replacing `/bin/cat` with a shell alias for `grep 'rafl'`.

**Comment by xsawyerx** [comment]
@tobyink you have been given a commit bit! Now you could commit your new contribution. Thank you. :)
(I should note this isn't because I don't want to do it myself, but rather because you're simply part of this now)

**Comment by xsawyerx** [comment]
Added, thanks! :)
